receivers:
  # Filelog Receiver
  filelog/meraki:
    include: [/tmp/jarvislogs/meraki/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "meraki"
      dataSource.vendor: "cisco"

  filelog/f5:
    include: [/tmp/jarvislogs/f5/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "f5"
      dataSource.vendor: "f5"

  filelog/fortigate:
    include: [/tmp/jarvislogs/forti/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "fortigate"
      dataSource.vendor: "fortigate"

  filelog/netskope:
    include: [/tmp/jarvislogs/netskope/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "netskope"
      dataSource.vendor: "netskope"

  filelog/palo:
    include: [/tmp/jarvislogs/palo/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "paloalto"
      dataSource.vendor: "paloalto"

  filelog/mimecast:
    include: [/tmp/jarvislogs/mimecast/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "mimecast"
      dataSource.vendor: "mimecast"

  filelog/zscaler:
    include: [/tmp/jarvislogs/zscaler/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "zscaler"
      dataSource.vendor: "zscaler"

  filelog/proofpoint:
    include: [/tmp/jarvislogs/proofpoint/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "Proofpoint"
      dataSource.vendor: "Proofpoint"

  filelog/googlews:
    include: [/tmp/jarvislogs/google/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "Google WorkSpace"
      dataSource.vendor: "Google"

  filelog/wel:
    include: [/tmp/jarvislogs/wel/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "Windows Event Logs"
      dataSource.vendor: "Microsoft"

  filelog/okta:
    include: [/tmp/jarvislogs/okta/*.log]
    start_at: beginning
    operators:
    include_file_name: true
    poll_interval: 1s
    attributes:
      dataSource.name: "Okta"
      dataSource.vendor: "Okta"

processors:
  # Batches logs for efficient export
  batch:
    timeout: 10s
    send_batch_size: 1000

  # Enrich
  attributes/add_metadata:
    actions:
      - key: dataSource.category
        value: "security"
        action: insert
      - key: sourcetype
        value: "Jarvis"
        action: insert

  attributes/add_metadata_meraki:
    actions:
      - key: parser
        value: "meraki"
        action: insert

  attributes/add_metadata_f5:
    actions:
      - key: parser
        value: "f5"
        action: insert

  attributes/add_metadata_fortigate:
    actions:
      - key: parser
        value: "fortigate"
        action: insert

  attributes/add_metadata_netskope:
    actions:
      - key: parser
        value: "netskope"
        action: insert

  attributes/add_metadata_palo:
    actions:
      - key: parser
        value: "palo"
        action: insert

  attributes/add_metadata_mimecast:
    actions:
      - key: parser
        value: "mimecast"
        action: insert

  attributes/add_metadata_zscaler:
    actions:
      - key: parser
        value: "zscaler"
        action: insert

  attributes/add_metadata_proofpoint:
    actions:
      - key: parser
        value: "proofpoint"
        action: insert

  attributes/add_metadata_googlews:
    actions:
      - key: parser
        value: "googlews"
        action: insert

  attributes/add_metadata_wel:
    actions:
      - key: parser
        value: "windowseventlogs"
        action: insert

  attributes/add_metadata_okta:
    actions:
      - key: parser
        value: "okta"
        action: insert

exporters:
  otlp:
    endpoint: "104.197.40.197:8016"

service:
  pipelines:
    logs/filelog/meraki:
      receivers: [filelog/meraki]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_meraki]
      exporters: [otlp]

    logs/filelog/f5:
      receivers: [filelog/f5]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_f5]
      exporters: [otlp]

    logs/filelog/fortigate:
      receivers: [filelog/fortigate]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_fortigate]
      exporters: [otlp]

    logs/filelog/netskope:
      receivers: [filelog/netskope]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_netskope]
      exporters: [otlp]

    logs/filelog/palo:
      receivers: [filelog/palo]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_palo]
      exporters: [otlp]

    logs/filelog/mimecast:
      receivers: [filelog/mimecast]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_mimecast]
      exporters: [otlp]

    logs/filelog/zscaler:
      receivers: [filelog/zscaler]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_zscaler]
      exporters: [otlp]

    logs/filelog/proofpoint:
      receivers: [filelog/proofpoint]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_proofpoint]
      exporters: [otlp]

    logs/filelog/googlews:
      receivers: [filelog/googlews]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_googlews]
      exporters: [otlp]

    logs/filelog/wel:
      receivers: [filelog/wel]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_wel]
      exporters: [otlp]

    logs/filelog/okta:
      receivers: [filelog/okta]
      processors: [batch,attributes/add_metadata,attributes/add_metadata_okta]
      exporters: [otlp]